### ISSUE TITLE
Champs attributaires différents en fonction de la langue

### ISSUE THREAD

**Issue by mt111** [geoportallux/geoportailv3-gisgr#30]
Nous avons des services avec des champs contenat des valeurs différentes pour chacune des 3 langues utilisées (de, en,fr)

Est-ce que nous allons préfixer ces champs de la manière suivante ?
- de_entity
- en_entity
- fr_entity 

Certains services peuvent avoir plusieurs champs de ce type, d'autres qu'un seul (càd 3 pour les 3 langues) et encore d'autres pour lesquels nous n'avons pas de traduction et pour lesquels nous pouvons utiliser le template standard

**Comment by rmichaelis** [comment]
Je vais modifier le "template" par défaut. 
Lorsque je rencontre, un attribut du type "xx_entity" j'afficherai uniquement celui qui correspond à la langue courante.
Si c'est un attribut de type "entity" je l'affiche sans me soucier de la langue.

**Comment by rmichaelis** [comment]
Bonjour,

Je suis en train de modifier le code  pour fonctionner comme prévu dans le ticket ci-dessus.
Par contre, j'ai remarqué que pour la couche Pop_TerrAggr_Evo_19 que les champs sont du type entity_D (une seule lettre et à la fin)
Contrairement à la couche CORINE_Land_Cover_2 où les champs sont du type de_category (2 lettres et en début)

Est-on d'accord que c'est bien la deuxième notation (2 lettres et en début) qui est la bonne ?

Merci

**Comment by mt111** [comment]
Bonjour,

on est d'accord pour la deuxième notation (2 lettres en début)

On va changer pour le service Pop_TerrAggr_eEvo_1990_2000 resp. pour les autres ou c'est encore la première variante

Merci
